version: '3.8'

name: url-shortener-dev

services:
  # API service for development with hot-reloading
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder  # Use only builder stage for development
    image: url-shortener-api:dev
    container_name: url-shortener-api-dev
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=url_shortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=debug
      - API_PREFIX=/api
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
      - RELOAD=true
    volumes:
      - ../app:/app/app  # Mount app directory for hot reloading
      - ../migrations:/app/migrations
      - ../alembic.ini:/app/alembic.ini
      - app_logs_dev:/app/logs
    networks:
      - app_network_dev
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # No health check in dev mode to avoid issues during code changes

  # PostgreSQL database for development
  db:
    image: postgres:16.9-bullseye
    container_name: url-shortener-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"  # Expose port for local development tools
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ../init-scripts:/docker-entrypoint-initdb.d  # Initialize with scripts
    networks:
      - app_network_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis for development
  redis:
    image: redis:7.2-alpine
    container_name: url-shortener-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"  # Expose port for local development tools
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    networks:
      - app_network_dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Optional: pgAdmin for database management in development
  pgadmin:
    image: dpage/pgadmin4
    container_name: url-shortener-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network_dev
    depends_on:
      - db

volumes:
  postgres_data_dev:
    name: url-shortener-postgres-data-dev
  redis_data_dev:
    name: url-shortener-redis-data-dev
  app_logs_dev:
    name: url-shortener-logs-dev
  pgadmin_data:
    name: url-shortener-pgadmin-data

networks:
  app_network_dev:
    name: url-shortener-network-dev 