"""recreate_all_tables

Revision ID: 07873390d51b
Revises: 
Create Date: 2025-05-14 04:07:48.583095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07873390d51b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index('ix_short_urls_click_count', 'short_urls', ['click_count'], unique=False)
    op.create_index('ix_short_urls_code_expiry', 'short_urls', ['short_code', 'expires_at'], unique=False)
    op.create_index('ix_short_urls_created_at', 'short_urls', ['created_at'], unique=False)
    op.create_index(op.f('ix_short_urls_expires_at'), 'short_urls', ['expires_at'], unique=False)
    op.create_table('click_events',
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['short_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_click_events_clicked_at', 'click_events', ['clicked_at'], unique=False)
    op.create_index('ix_click_events_url_id_clicked_at', 'click_events', ['url_id', 'clicked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_click_events_url_id_clicked_at', table_name='click_events')
    op.drop_index('ix_click_events_clicked_at', table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_short_urls_expires_at'), table_name='short_urls')
    op.drop_index('ix_short_urls_created_at', table_name='short_urls')
    op.drop_index('ix_short_urls_code_expiry', table_name='short_urls')
    op.drop_index('ix_short_urls_click_count', table_name='short_urls')
    op.drop_table('short_urls')
    # ### end Alembic commands ###
